[versions]
agp = "9.2.1"
publisher = "9.2.5"
android-annotation = "1.10.0"
libxposed-annotation = "1.0.0"
libxposed-lint = "1.0.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
publish-central = { id = "org.danilopianini.publish-on-central", version.ref = "publisher" }

[libraries]
android-annotation = { module = "androidx.annotation:annotation", version.ref = "android-annotation" }
libxposed-annotation = { module = "io.github.libxposed:annotation", version.ref = "libxposed-annotation" }
libxposed-lint = { module = "io.github.libxposed:lint", version.ref = "libxposed-lint" }